// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtprysdowazgjahzgmch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0cHJ5c2Rvd2F6Z2phaHpnbWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTQ3MjUsImV4cCI6MjA3MzE5MDcyNX0.moUmSasTc5XfLn5YgRkRgMLSCqwbtBeMtFI1_V7kVWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});